### ISSUE TITLE
Configurable list of users who cannot award points e.g. AutoModerator, abusers

### ISSUE THREAD

**Issue by epicmindwarp** [fsvreddit/reputatorbot#15]
Some users should be prevented from awarding points - such as Automoderator when it sends reminder prompts.

https://www.reddit.com/r/excel/comments/1begyup/how_to_xlookup_for_text_in_a_column_of_numbers/kut9147/

This is also a seperate bug to a mod awarding points.

**Comment by fsvreddit** [comment]
As a workaround to this, you could demod AutoModerator. AutoMod doesn't need to actually be in the mod list to be able to award points now.

**Comment by epicmindwarp** [comment]
Have added to the exclusion list for now!
