### ISSUE TITLE
r/Excel needs the flair store to read only from the current flair

### ISSUE THREAD

**Issue by epicmindwarp** [fsvreddit/reputatorbot#38]
Have an option to not use the redis db when incrementing the flair.

r/Excel regularly audits points to prevent double counts; in these cases the datbase sometimes returns a flair value that's different to the user's current flair because mods have deducted points.

In these cases, we want the sub to manually set their flairs, and the bot to set just +1

**Comment by epicmindwarp** [comment]
Have added suggested code change here

https://github.com/epicmindwarp/reputatorbot/commits/main/

**Comment by fsvreddit** [comment]
Just a thought, might it be better to have an option to manually set a user's score, meaning that /r/Excel could deduct points "properly", being reflected in both the database and the flair?

**Comment by epicmindwarp** [comment]
The mods want to update the flair text freely, they wouldn't want to change that workflow.

In theory devvti should be able to handle for this and update the db, if the trigger is a user flair update for specific template Id or css class.

**Comment by fsvreddit** [comment]
I've implemented a variation on your idea anyway. It won't disregard the Redis value, but if the option is on and a flair is set, the flair will always take precedence.

**Comment by fsvreddit** [comment]
Oh, and unfortunately there's no way to react to a user flair update, but the database would be updated properly the next time that user was granted a point.
